### ISSUE TITLE
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

### ISSUE THREAD

**Issue by JeetShah10** [tom-doerr/audio_adversarial_examples#1]
While running this command
$ docker run -it --mount src=$(pwd),target=/audio_adversarial_examples,type=bind -w /audio_adversarial_examples aae_deepspeech_041_cpu
I am getting this "the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'".
I don't understand what to do. Can you help solving this?

**Comment by tom-doerr** [comment]
That's strange.
Are you using Windows?
Which terminal emulator are you using?

**Comment by JeetShah10** [comment]
@tom-doerr  Yes I am using Windows and GIT bash terminal

**Comment by tom-doerr** [comment]
This should work:
```
winpty docker run -it --mount src=$(pwd),target=/audio_adversarial_examples,type=bind -w /audio_adversarial_examples aae_deepspeech_041_cpu
```
More info: https://stackoverflow.com/questions/48623005/docker-error-the-input-device-is-not-a-tty-if-you-are-using-mintty-try-prefi

**Comment by JeetShah10** [comment]
@tom-doerr I tried this:
winpty docker run -it --mount src=$(pwd),target=/audio_adversarial_examples,type=bind -w /audio_adversarial_examples aae_deepspeech_041_cpu

but I was getting this error:
C:/Program Files/Docker Toolbox/docker.exe: Error response from daemon: the work
ing directory 'C:/Program Files/Git/audio_adversarial_examples' is invalid, it n
eeds to be an absolute path.
See 'C:/Program Files/Docker Toolbox/docker.exe run --help'.

**Comment by tom-doerr** [comment]
Could you try this in Powershell?
If that doesn't work you could use the Windows Subsystem for Linux.

**Comment by JeetShah10** [comment]
@tom-doerr Tried in Powershell but now I'm getting this after running $ ./setup.sh command:

![Capture](https://user-images.githubusercontent.com/43672173/81805579-f81cce80-94cf-11ea-8c1e-4468f817ab01.JPG)

And then by running command:
$ docker run -it --mount src=$(pwd),target=/audio_adversarial_examples,type=bind -w /audio_adversarial_examples aae_deepspeech_041_cpu

getting this error:

![Capture1](https://user-images.githubusercontent.com/43672173/81806125-e25bd900-94d0-11ea-94f7-d6b3cce01ed0.JPG)

**Comment by tom-doerr** [comment]
The Windows Subsystem for Linux seems like your best option.

**Comment by tom-doerr** [comment]
I assume you got it running using the WSL.
